language: bash
services: docker

env:
  - VERSION=7.3 VARIANT=cli
  - VERSION=7.3 VARIANT=web
  - VERSION=7.3 VARIANT=rr
  - VERSION=7.4 VARIANT=cli
  - VERSION=7.4 VARIANT=web


before_script:
  - env | sort

script:
  - export BUILD_BASE=fluxoti/php
  - travis_retry make

after_script:
  - docker images
