language: bash
services: docker

env:
  - VERSION=7.4 VARIANT=cli
  - VERSION=7.4 VARIANT=web
  - VERSION=8.0 VARIANT=web
  - VERSION=8.0 VARIANT=cli

before_script:
  - env | sort

script:
  - export BUILD_BASE=fluxoti/php
  - travis_retry make

after_script:
  - docker images
