language: bash
services: docker

env:
  - VERSION=7.1 VARIANT=cli
  - VERSION=7.1 VARIANT=web

before_script:
  - env | sort

script:
  - export BUILD_BASE=fluxoti/php
  - travis_retry make

after_script:
  - docker images