language: bash
services: docker

env:
  - VERSION=7.1 VARIANT=cli
  - VERSION=7.1 VARIANT=web
  - VERSION=7.2 VARIANT=cli
  - VERSION=7.2 VARIANT=web
  - VERSION=7.2 VARIANT=pm
  - VERSION=7.3 VARIANT=cli
  - VERSION=7.3 VARIANT=web
  - VERSION=7.3 VARIANT=pm

before_script:
  - env | sort

script:
  - export BUILD_BASE=fluxoti/php
  - travis_retry make

after_script:
  - docker images